# Make sure to check the documentation at http://goreleaser.com

builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  - arm
  - arm64
  - 386
  goos:
  - linux
  - darwin
  goarm:
  - 7

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Major }}-snapshot"

dockers:
- image_templates:
  - "docker.io/vshn/rclone-exporter:v{{ .Version }}"
  - "docker.io/vshn/rclone-exporter:v{{ .Major }}"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  github:
    owner: vshn
    name: rclone-exporter
